In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
#Binary Class Classification
from sklearn.datasets import make_classification

In [19]:
X,Y=make_classification(n_samples=1000,n_features=10,n_classes=2,random_state=12)

In [20]:
X

array([[-1.36188762, -0.38852555, -0.68700494, ..., -0.59993549,
         1.65727569,  0.58826194],
       [-1.55907147, -0.32641019,  0.17057821, ..., -1.1032606 ,
        -0.2999431 ,  2.57855637],
       [ 0.74830157,  0.51136195,  0.65880056, ..., -0.25711479,
        -0.03294953,  1.3797154 ],
       ...,
       [-0.36477962,  0.32379489, -0.21190752, ...,  0.7912045 ,
         1.16610239,  1.85482198],
       [ 0.92183889, -0.41570846, -0.018183  , ...,  0.47486451,
         0.61097645, -0.51431929],
       [ 0.3040265 , -0.14998645, -0.65565164, ...,  2.15265808,
        -0.948752  ,  0.20148097]])

In [21]:
Y

array([1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,

In [22]:
pd.DataFrame(X)

0         1         2         3         4         5         6  \
0   -1.361888 -0.388526 -0.687005  0.054313 -1.085694  1.122830 -1.338670   
1   -1.559071 -0.326410  0.170578  0.289913  1.304315  1.280638 -0.916428   
2    0.748302  0.511362  0.658801 -0.434340  0.701522 -1.588531 -0.375476   
3   -0.315214 -0.767714  0.369249 -0.330236  2.973036  2.997636  0.678615   
4   -1.654782 -0.048819 -0.119700 -1.297692 -0.235352  0.126030 -1.416322   
..        ...       ...       ...       ...       ...       ...       ...   
995 -0.116902  0.228621 -0.254905  0.928581 -1.314989 -0.958066 -0.577889   
996 -0.463243  0.480664 -0.549567 -0.123899 -2.805139 -2.020440 -0.608644   
997 -0.364780  0.323795 -0.211908 -0.445859 -1.420422 -1.289637  0.046983   
998  0.921839 -0.415708 -0.018183  0.782068  0.963305  1.524786  0.721108   
999  0.304026 -0.149986 -0.655652  0.772343 -1.576442  0.257325  0.252415   

            7         8         9  
0   -0.599935  1.657276  0.588262  
1   -1.103261 -0.299943  2.578556  
2   -0.257115 -0.032950  1.379715  
3   -0.034100  1.276816 -1.215973  
4    1.106680 -1.588829 -1.557777  
..        ...       ...       ...  
995 -0.155235 -0.624097 -0.455986  
996  0.485689  0.692041  0.938690  
997  0.791205  1.166102  1.854822  
998  0.474865  0.610976 -0.514319  
999  2.152658 -0.948752  0.201481  

[1000 rows x 10 columns]

In [23]:
#train test split
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.30,random_state=42)

In [24]:
#model training
from sklearn.linear_model import LogisticRegression
logistic = LogisticRegression()

In [25]:
logistic.fit(X_train,Y_train)

LogisticRegression()

In [26]:
#prediction
y_pred = logistic.predict(X_test)
print(y_pred)

[0 1 1 1 1 1 1 0 1 0 0 0 1 0 0 0 1 1 0 0 1 1 1 0 1 1 1 1 1 0 0 0 1 1 1 1 1
 0 1 0 1 1 1 0 0 0 0 1 0 0 1 0 1 1 1 0 0 0 0 0 1 0 0 0 0 1 0 1 1 1 0 1 0 0
 0 1 1 0 0 0 0 1 1 1 0 0 1 0 0 1 0 0 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 0 0 1 0
 0 0 1 0 1 1 0 1 0 1 0 0 0 1 0 0 0 1 1 1 1 1 0 1 0 0 0 1 1 0 1 1 1 1 0 1 0
 0 1 1 0 0 0 1 0 1 0 1 0 1 1 0 1 1 0 1 0 1 1 1 0 0 0 0 0 1 1 1 1 1 0 0 0 0
 1 0 0 0 0 0 1 0 0 1 1 1 1 1 1 0 0 0 0 1 0 1 0 0 1 0 0 0 0 1 1 0 1 1 0 0 0
 0 0 1 0 0 1 1 0 0 1 1 1 1 1 1 1 0 0 1 1 1 0 1 1 1 0 1 0 1 1 0 0 0 0 0 0 0
 0 0 1 1 1 1 0 0 0 1 1 0 1 1 1 1 1 0 1 0 1 1 0 1 1 0 0 1 0 1 1 0 0 0 0 1 1
 0 1 0 0]


In [27]:
#probability - if you want to see the probability of output feature which falls under which category
logistic.predict_proba(X_test)

array([[8.41902772e-01, 1.58097228e-01],
       [1.75443509e-02, 9.82455649e-01],
       [9.90791245e-02, 9.00920876e-01],
       [8.89828277e-02, 9.11017172e-01],
       [6.68803717e-03, 9.93311963e-01],
       [2.49810708e-04, 9.99750189e-01],
       [3.25445928e-04, 9.99674554e-01],
       [6.18648838e-01, 3.81351162e-01],
       [2.62192897e-01, 7.37807103e-01],
       [9.99688136e-01, 3.11864030e-04],
       [9.52840380e-01, 4.71596199e-02],
       [9.42730393e-01, 5.72696070e-02],
       [5.35561749e-02, 9.46443825e-01],
       [9.78781231e-01, 2.12187694e-02],
       [7.41511576e-01, 2.58488424e-01],
       [9.85999138e-01, 1.40008621e-02],
       [2.20765491e-01, 7.79234509e-01],
       [1.26552492e-01, 8.73447508e-01],
       [9.93891242e-01, 6.10875774e-03],
       [9.54404040e-01, 4.55959597e-02],
       [1.87819913e-01, 8.12180087e-01],
       [3.75653527e-01, 6.24346473e-01],
       [3.85917154e-02, 9.61408285e-01],
       [5.15279305e-01, 4.84720695e-01],
       [4.632907

In [28]:
#Performance metrics
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [29]:
score = accuracy_score(Y_test,y_pred)
print(score)


0.8766666666666667


In [30]:
cm = confusion_matrix(Y_test,y_pred)
print(cm)

[[136  20]
 [ 17 127]]


In [31]:
print(classification_report(Y_test,y_pred))

              precision    recall  f1-score   support

           0       0.89      0.87      0.88       156
           1       0.86      0.88      0.87       144

    accuracy                           0.88       300
   macro avg       0.88      0.88      0.88       300
weighted avg       0.88      0.88      0.88       300



In [78]:
#Hyper_Parameter_Tunningg
#Cross_Validation - Grid search cv and randomized search cv

model = LogisticRegression()
#penalty = ['l1','l2','elasticnet'] #out of all params which is the best one to choose
penalty = ['l2','none',]
c_values = [100,10,1.0,0.1,0.01]
solver = ['newton-cg','lbfgs','sag','saga']
#solver = ['newton-cg']

#model = LogisticRegression(C=0.01, penalty='l1',solver='liblinear');

In [79]:
#arrange or make it as a key value pair
params=dict(penalty=penalty,C=c_values,solver=solver)
params

{'penalty': ['l2', 'none'],
 'C': [100, 10, 1.0, 0.1, 0.01],
 'solver': ['newton-cg', 'lbfgs', 'sag', 'saga']}

In [80]:
#Hyperparameter tunning - GridSearchCV
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedKFold
cv = StratifiedKFold()
grid1 = GridSearchCV(estimator=model,
                    param_grid=params,
                    scoring='accuracy',
                    cv=cv,
                    n_jobs=-1)

In [81]:
grid1

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l2', 'none'],
                         'solver': ['newton-cg', 'lbfgs', 'sag', 'saga']},
             scoring='accuracy')

In [82]:
#fit with our train data
grid1.fit(X_train,Y_train)

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l2', 'none'],
                         'solver': ['newton-cg', 'lbfgs', 'sag', 'saga']},
             scoring='accuracy')

In [83]:
grid1.best_params_

{'C': 0.01, 'penalty': 'l2', 'solver': 'newton-cg'}

In [84]:
grid1.best_score_

0.8714285714285716

In [85]:
y_pred1 = grid1.predict(X_test)

In [86]:
#Performance metrics
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [87]:
score = accuracy_score(Y_test,y_pred1)
print(score)
cm = confusion_matrix(Y_test,y_pred1)
print(cm)
print(classification_report(Y_test,y_pred1))

0.8633333333333333
[[135  21]
 [ 20 124]]
              precision    recall  f1-score   support

           0       0.87      0.87      0.87       156
           1       0.86      0.86      0.86       144

    accuracy                           0.86       300
   macro avg       0.86      0.86      0.86       300
weighted avg       0.86      0.86      0.86       300

