In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
#Multi Class Classification
from sklearn.datasets import make_classification

In [18]:
#3 categories
X,Y=make_classification(n_samples=1000,n_informative=3,n_features=10,n_classes=3,random_state=42)

In [19]:
X

array([[ 0.7715326 , -1.47433614,  2.19664605, ...,  0.68174341,
         1.08996189,  0.96250289],
       [ 1.85838284, -3.68087983,  0.22749588, ..., -0.47417818,
         1.34113888, -0.77177196],
       [-0.98724764,  1.53916836,  0.5859042 , ..., -0.32202815,
        -1.45103394,  1.32543211],
       ...,
       [-1.227082  ,  1.65602784,  0.47263035, ..., -0.8634936 ,
        -1.83932326, -0.03120349],
       [ 1.28527572, -0.29715202, -0.67172079, ..., -1.31544131,
         2.85446468,  1.3094441 ],
       [-0.75428048,  0.88516075, -1.6728939 , ..., -2.0362205 ,
        -1.43989584,  0.04749347]])

In [20]:
Y

array([1, 2, 1, 1, 2, 1, 1, 0, 2, 2, 2, 0, 1, 0, 2, 1, 2, 1, 0, 1, 1, 1,
       2, 2, 1, 2, 2, 0, 1, 2, 0, 1, 0, 2, 0, 1, 0, 0, 2, 0, 1, 0, 2, 1,
       2, 0, 2, 0, 2, 0, 0, 0, 2, 1, 1, 1, 1, 2, 0, 0, 2, 1, 0, 0, 1, 2,
       0, 2, 2, 1, 0, 1, 1, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0,
       0, 1, 1, 2, 1, 0, 1, 2, 0, 2, 0, 0, 2, 1, 0, 2, 0, 2, 2, 0, 2, 0,
       0, 0, 0, 2, 1, 2, 1, 0, 2, 0, 0, 2, 1, 0, 2, 1, 0, 0, 2, 2, 0, 0,
       0, 2, 1, 2, 2, 0, 2, 0, 1, 2, 1, 2, 1, 1, 2, 0, 0, 1, 0, 2, 0, 0,
       0, 1, 1, 2, 1, 2, 2, 0, 0, 0, 1, 1, 0, 2, 1, 2, 2, 2, 1, 1, 0, 2,
       1, 0, 2, 1, 2, 1, 2, 0, 1, 1, 0, 2, 2, 2, 2, 0, 2, 0, 0, 0, 0, 2,
       1, 2, 1, 1, 0, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 2, 2, 0, 2, 2, 2, 0,
       2, 0, 1, 1, 2, 1, 2, 2, 2, 2, 0, 1, 0, 0, 0, 0, 2, 2, 2, 1, 1, 1,
       0, 2, 0, 0, 1, 0, 2, 0, 1, 2, 2, 2, 1, 2, 1, 0, 1, 1, 1, 2, 2, 2,
       2, 2, 2, 0, 0, 0, 2, 1, 1, 1, 1, 2, 1, 2, 2, 1, 2, 1, 0, 0, 2, 2,
       2, 1, 1, 1, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 1,

In [21]:
#train test split
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.30,random_state=12)

In [22]:
#model training
from sklearn.linear_model import LogisticRegression
logistic = LogisticRegression(multi_class='ovr')
logistic.fit(X_train,Y_train)
y_pred = logistic.predict(X_test)

In [23]:
y_pred

array([1, 0, 2, 2, 2, 0, 0, 0, 0, 1, 1, 2, 1, 0, 0, 0, 2, 2, 0, 2, 0, 2,
       0, 1, 1, 0, 2, 0, 1, 2, 1, 0, 2, 0, 0, 0, 2, 2, 0, 2, 0, 2, 0, 2,
       2, 2, 2, 1, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 2, 2, 1, 1, 1, 0, 0, 2,
       2, 1, 0, 2, 2, 0, 0, 0, 0, 1, 0, 2, 1, 0, 2, 2, 2, 0, 2, 2, 2, 0,
       2, 2, 2, 1, 1, 1, 0, 0, 1, 2, 2, 0, 1, 2, 0, 2, 0, 0, 0, 0, 0, 0,
       0, 0, 2, 2, 2, 2, 1, 2, 2, 1, 1, 2, 2, 2, 2, 1, 0, 0, 0, 2, 0, 0,
       0, 1, 2, 0, 0, 2, 1, 0, 0, 2, 0, 0, 1, 1, 0, 0, 2, 0, 2, 0, 0, 1,
       2, 0, 2, 0, 0, 1, 2, 1, 2, 0, 1, 0, 0, 2, 0, 2, 1, 2, 0, 1, 0, 0,
       2, 2, 2, 0, 1, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0,
       2, 2, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 2, 2, 2, 0, 0, 1, 1, 0,
       2, 1, 0, 0, 0, 0, 1, 1, 2, 2, 0, 0, 1, 2, 2, 2, 0, 0, 0, 2, 2, 0,
       1, 1, 2, 2, 0, 2, 2, 2, 1, 2, 1, 1, 2, 0, 0, 1, 1, 0, 2, 2, 1, 0,
       2, 0, 1, 0, 2, 0, 2, 2, 2, 1, 2, 0, 1, 2, 1, 0, 0, 1, 1, 0, 1, 1,
       2, 2, 1, 0, 0, 2, 2, 1, 0, 0, 2, 1, 0, 0])

In [24]:
#Performance metrics
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

score = accuracy_score(Y_test,y_pred)
print(score)
cm = confusion_matrix(Y_test,y_pred)
print(cm)
print(classification_report(Y_test,y_pred))

0.6566666666666666
[[80 22  6]
 [42 38 19]
 [ 6  8 79]]
              precision    recall  f1-score   support

           0       0.62      0.74      0.68       108
           1       0.56      0.38      0.46        99
           2       0.76      0.85      0.80        93

    accuracy                           0.66       300
   macro avg       0.65      0.66      0.65       300
weighted avg       0.64      0.66      0.64       300



In [25]:
model = LogisticRegression()

penalty = ['l2','none',]
c_values = [100,10,1.0,0.1,0.01]
solver = ['newton-cg','lbfgs','sag','saga']




In [26]:
#arrange or make it as a key value pair
params=dict(penalty=penalty,C=c_values,solver=solver)
params

{'penalty': ['l2', 'none'],
 'C': [100, 10, 1.0, 0.1, 0.01],
 'solver': ['newton-cg', 'lbfgs', 'sag', 'saga']}

In [27]:
#HyperParameter Tunning
from sklearn.model_selection import RandomizedSearchCV
model1 = LogisticRegression()
randomcv = RandomizedSearchCV(estimator=model1,
                              param_distributions=params,
                              cv=5,
                              scoring='accuracy')

In [28]:
randomcv.fit(X_train,Y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:1183: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:1193: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:1183: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:1193: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:1183: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [100, 10, 1.0, 0.1, 0.01],
                                        'penalty': ['l2', 'none'],
                                        'solver': ['newton-cg', 'lbfgs', 'sag',
                                                   'saga']},
                   scoring='accuracy')

In [29]:
randomcv.best_score_

0.6528571428571428

In [30]:
randomcv.best_params_

{'solver': 'newton-cg', 'penalty': 'l2', 'C': 0.1}

In [31]:
y_pred1=randomcv.predict(X_test)

In [32]:
score1 = accuracy_score(Y_test,y_pred1)
print(score1)
cm1 = confusion_matrix(Y_test,y_pred1)
print(cm1)
print(classification_report(Y_test,y_pred1))

0.62
[[69 35  4]
 [35 45 19]
 [ 4 17 72]]
              precision    recall  f1-score   support

           0       0.64      0.64      0.64       108
           1       0.46      0.45      0.46        99
           2       0.76      0.77      0.77        93

    accuracy                           0.62       300
   macro avg       0.62      0.62      0.62       300
weighted avg       0.62      0.62      0.62       300

