In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn.datasets import make_classification

In [3]:
#classweights parameter to make imbalance datasets

#Make a imbalanced datasets for a binary class classification

X,Y = make_classification(n_samples=10000,
                          n_features=2,
                          n_clusters_per_class=1,
                          n_redundant=0,
                          weights=[0.99],
                          random_state=10)

In [4]:
X

array([[ 1.87991016, -1.4850347 ],
       [ 0.37708311, -2.23858488],
       [ 1.35431163, -2.66463822],
       ...,
       [ 0.99509904, -0.54192355],
       [ 1.75859359, -1.54961188],
       [ 0.79770543, -1.99467372]])

In [5]:
Y

array([0, 0, 0, ..., 0, 0, 0])

In [9]:
from collections import Counter

Counter(Y)

Counter({0: 9846, 1: 154})

In [15]:
#X1=pd.DataFrame(X)[0]

In [24]:
#Y1=pd.DataFrame(X)[1]

In [26]:
#import seaborn as sns
#sns.scatterplot(pd.DataFrame(X)[0],pd.DataFrame(X)[1],hue=Y)

In [27]:
#split
#train test split
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.30,random_state=42)

In [29]:
#model training
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

#Hyperparameter tunning
penalty = ['l2','none',]
c_values = [100,10,1.0,0.1,0.01]
solver = ['newton-cg','lbfgs','sag','saga']
class_weight = [{0:w,1:y}for w in [1,10,50,100]for y in [1,10,50,100]]


In [30]:
params = dict(penalty=penalty,
           C=c_values,
           solver=solver,
           class_weight=class_weight)

In [31]:
params

{'penalty': ['l2', 'none'],
 'C': [100, 10, 1.0, 0.1, 0.01],
 'solver': ['newton-cg', 'lbfgs', 'sag', 'saga'],
 'class_weight': [{0: 1, 1: 1},
  {0: 1, 1: 10},
  {0: 1, 1: 50},
  {0: 1, 1: 100},
  {0: 10, 1: 1},
  {0: 10, 1: 10},
  {0: 10, 1: 50},
  {0: 10, 1: 100},
  {0: 50, 1: 1},
  {0: 50, 1: 10},
  {0: 50, 1: 50},
  {0: 50, 1: 100},
  {0: 100, 1: 1},
  {0: 100, 1: 10},
  {0: 100, 1: 50},
  {0: 100, 1: 100}]}

In [34]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedKFold
cv = StratifiedKFold()
grid = GridSearchCV(estimator=model,
                    param_grid=params,
                    scoring='accuracy',
                    cv=cv)

In [35]:
grid.fit(X_train,Y_train)

Streaming output truncated to the last 5000 lines.
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:1193: UserWarning: Setting penalty=None will ignore the C and l1_ratio parameters
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_sag.py:350: Co

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(),
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'class_weight': [{0: 1, 1: 1}, {0: 1, 1: 10},
                                          {0: 1, 1: 50}, {0: 1, 1: 100},
                                          {0: 10, 1: 1}, {0: 10, 1: 10},
                                          {0: 10, 1: 50}, {0: 10, 1: 100},
                                          {0: 50, 1: 1}, {0: 50, 1: 10},
                                          {0: 50, 1: 50}, {0: 50, 1: 100},
                                          {0: 100, 1: 1}, {0: 100, 1: 10},
                                          {0: 100, 1: 50}, {0: 100, 1: 100}],
                         'penalty': ['l2', 'none'],
                         'solver': ['newton-cg', 'lbfgs', 'sag', 'saga']},
             scoring='accuracy')

In [36]:
grid.best_params_

{'C': 0.01,
 'class_weight': {0: 10, 1: 50},
 'penalty': 'l2',
 'solver': 'newton-cg'}

In [38]:
y_pred = grid.predict(X_test)

In [39]:
#Performance metrics
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

score = accuracy_score(Y_test,y_pred)
print(score)
cm = confusion_matrix(Y_test,y_pred)
print(cm)
print(classification_report(Y_test,y_pred))

0.9886666666666667
[[2949    4]
 [  30   17]]
              precision    recall  f1-score   support

           0       0.99      1.00      0.99      2953
           1       0.81      0.36      0.50        47

    accuracy                           0.99      3000
   macro avg       0.90      0.68      0.75      3000
weighted avg       0.99      0.99      0.99      3000



In [ ]:
#In Confusion matrix
#4+30= 34 datapoints are classified incorrectly