In [2]:
import numpy as np

In [3]:
#create arrays using numpy
#Create 1dimensional array
ar1 = np.array([1,2,3,4,5])
print(ar1)

[1 2 3 4 5]


In [4]:
type(ar1)

numpy.ndarray

In [5]:
#shape of the array
print(ar1.shape)

(5,)


In [6]:
#reshape
ar2=np.array([1,2,3,4,5])
ar2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [7]:
type(ar2)

numpy.ndarray

In [10]:
print(ar2.shape) #1 row 5 columns

(5,)


In [11]:
ar3 = np.array([[1,2,3,4,5]])
ar3.shape

(1, 5)

In [12]:
#2dimensional array
ar4 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(ar4)

[[1 2 3 4 5]
 [2 3 4 5 6]]


In [13]:
print(ar4.shape) #2 rows and 5 columns

(2, 5)


In [14]:
#Arrays with Inbuilt functions
#arange
a1=np.arange(0,10)
print(a1) 

[0 1 2 3 4 5 6 7 8 9]


In [15]:
a2 = np.arange(0,10,2)
print(a2)

[0 2 4 6 8]


In [16]:
#reshape 
a3=np.arange(0,10,2).reshape(5,1)
print(a3)

[[0]
 [2]
 [4]
 [6]
 [8]]


In [17]:
print(a3.shape) #5 rows and 1 column

(5, 1)


In [18]:
#ones - Two dimensional array with 3 rows and 4 columns
o = np.ones((3,4))
print(o)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [19]:
#identity matrix - diagonal elements with value 1
i=np.eye(3)
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
#size - number of elements
print(i.size)

9


In [21]:
#dtype
i.dtype

dtype('float64')

In [22]:
#itemsize in bytes
i.itemsize

8

In [23]:
#Numpy Vectorized Operation
vo = np.array((1,2,3,4,5))
vo1 = np.array((20,30,40,50,60))

#element wise addition
print("Addition : ",vo+vo1)

Addition :  [21 32 43 54 65]


In [25]:
#element wise subtraction
print("Subtraction : ",vo1-vo)

Subtraction :  [19 28 37 46 55]


In [26]:
#element wise multiplication
print("Multiplication : ",vo1*vo)

Multiplication :  [ 20  60 120 200 300]


In [27]:
#universal function - Some function which applies to the entire array
ar = np.array([2,3,4,5,6])

#square root
print(np.sqrt(ar))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]


In [28]:
#Exponential
print(np.exp(ar))

[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]


In [29]:
#sine
print(np.sin(ar))

[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]


In [30]:
#natural log
print(np.log(ar))

[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [32]:
#Array slicing and indexing
arr1 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(arr1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [33]:
arr1[0]

array([1, 2, 3, 4, 5])

In [34]:
arr1[0][2]

np.int64(3)

In [35]:
arr1[1:]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [37]:
arr1[1:,3:]

array([[ 9, 10],
       [14, 15]])

In [38]:
arr1[0:2,1:]

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10]])

In [39]:
arr1[0:2,2:]

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [41]:
arr1[1:,2:4]

array([[ 8,  9],
       [13, 14]])

In [42]:
#modify array elements
arr1[0,1]=20

In [43]:
print(arr1)

[[ 1 20  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [44]:
arr1[1:]=20
print(arr1)

[[ 1 20  3  4  5]
 [20 20 20 20 20]
 [20 20 20 20 20]]


In [45]:
#statistical concept - Normalization
#Data with Mean of zero and standard deviation of one

data = np.array([1,2,3,4,5])

#calculate mean and standard deviation
mean = np.mean(data)
stdev = np.std(data)

#Normalize the data
normalize_data = (data-mean)/stdev
print("Normalized_Data : ", normalize_data)

Normalized_Data :  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [46]:
median = np.median(data)
variance = np.var(data)

print("Median : {} \nVariance : {}".format(median,variance))

Median : 3.0 
Variance : 2.0


In [47]:
#Logical operations
data= np.arange(1,10)
data>5

array([False, False, False, False, False,  True,  True,  True,  True])

In [48]:
data[data>5]

array([6, 7, 8, 9])

In [53]:
data[(data>5) | (data<=2)]

array([1, 2, 6, 7, 8, 9])

In [56]:
data[(data>=5) & (data<=6)]

array([5, 6])