In [2]:
import numpy as np

In [3]:
#create arrays using numpy
#Create 1dimensional array
ar1 = np.array([1,2,3,4,5])
print(ar1)

[1 2 3 4 5]


In [4]:
type(ar1)

numpy.ndarray

In [5]:
#shape of the array
print(ar1.shape)

(5,)


In [6]:
#reshape
ar2=np.array([1,2,3,4,5])
ar2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [7]:
type(ar2)

numpy.ndarray

In [10]:
print(ar2.shape) #1 row 5 columns

(5,)


In [11]:
ar3 = np.array([[1,2,3,4,5]])
ar3.shape

(1, 5)

In [12]:
#2dimensional array
ar4 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(ar4)

[[1 2 3 4 5]
 [2 3 4 5 6]]


In [13]:
print(ar4.shape) #2 rows and 5 columns

(2, 5)
